---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: platform
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  title: Example Website
  annotations:
    is3-devportal/version-conso: "http://localhost:4000/conso/version"
    is3-devportal/version-int: "http://localhost:4000/int/version"
    is3-devportal/version-pre: "http://localhost:4000/pre/version"
    is3-devportal/version-pro: "http://localhost:4000/pro/version"
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-mobile-app
  title: Example Mobile App
  annotations:
    is3-devportal/version-conso: "http://localhost:4000/conso/version"
    is3-devportal/version-int: "http://localhost:4000/int/version"
    is3-devportal/version-pre: "http://localhost:4000/pre/version"
    is3-devportal/version-pro: "http://localhost:4000/pro/version"
spec:
  type: mobile
  lifecycle: production
  owner: guests
  system: examples
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platform-api-gateway
  title: API Gateway
  annotations:
    is3-devportal/version-conso: "http://localhost:4001/conso/version"
    is3-devportal/version-int: "http://localhost:4001/int/version"
    is3-devportal/version-pre: "http://localhost:4001/pre/version"
    is3-devportal/version-pro: "http://localhost:4001/pro/version"
spec:
  type: service
  lifecycle: production
  owner: guests
  system: platform
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
